<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Z51" failures="1" tests="4" name="Test" time="29.989" errors="0" timestamp="2021-10-08T12:59:18 IST">
  <testcase classname="tests.FourTest" name="Fourtest" time="8.174"/>
  <testcase classname="tests.TwoTest" name="Twotest" time="6.025"/>
  <testcase classname="tests.ThreeTest" name="threetest" time="4.674"/>
  <testcase classname="tests.LoginTest" name="login" time="6.288">
    <failure type="java.lang.AssertionError" message="expected [Successfull] but found [Successful]">
      <![CDATA[java.lang.AssertionError: expected [Successfull] but found [Successful]
at tests.LoginTest.login(LoginTest.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test -->
